language: android
android:
  components:
    # Uncomment the lines below if you want to
    # use the latest revision of Android SDK Tools
     #- platform-tools
     #- tools

    # The BuildTools version used by your project
    - build-tools-23.0.2
    - tools
    - platform-tools

    # The SDK version used to compile your project
    - android-23
before_script:
  - chmod +x gradlew

script:
   - ./gradlew build connectedCheck
